Name = "Soup.Test.Cpp"
Language = "C#|0.1"
Version = "0.2.1"
Source = [
	"Tasks/TestBuildTask.cs",
]

[Dependencies]
Runtime = [
	{ Reference = "Opal@1.0.3" },
	{ Reference = "Soup.Build@0.1.4", ExcludeRuntime = true },
	{ Reference = "Soup.Build.Extensions@0.2.0" },
	{ Reference = "Soup.Cpp.Compiler@0.3.1" },
	{ Reference = "Soup.Cpp.Compiler.MSVC@0.3.1" },
]