Name = "Soup.Test.Cpp"
Language = "C#"
Version = "0.1.4"
Source = [
	"Tasks/TestBuildTask.cs",
]

[Dependencies]
Runtime = [
	{ Reference = "Opal@1.0.1" },
	{ Reference = "Soup.Build@0.1.3", ExcludeRuntime = true },
	{ Reference = "Soup.Build.Extensions@0.1.8" },
	{ Reference = "Soup.Cpp.Compiler@0.1.6" },
	{ Reference = "Soup.Cpp.Compiler.MSVC@0.1.7" },
]