Name = "Cpp.Sample"
Language = "C++"
Version = "1.0.0"
Interface = "MyClass.cpp"

[Dependencies]
Runtime = [
	"../HelperDLL/",
]
Build = [
	"../TestBuild/"
]

[Tests]
Source = [
	"MyClass.UnitTests.cpp",
]